name: test

on:
  push:
    branches:
    - main
    
jobs:
  Might:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '14.x'
      - uses: microsoft/playwright-github-action@v1
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Upload any errors
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: might.error.*.png
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./__coverage__/
      #     fail_ci_if_error: false